name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */6 * * *' # A cada 6 horas
  workflow_dispatch: # Permite execução manual

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats Card
        uses: teoxoy/profile-readme-stats@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Activity Graph
        uses: Ashutosh00710/github-readme-activity-graph@v1
        with:
          username: Lucchesy0
          theme: tokyo-night
          output: github-activity.svg

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update stats [skip ci]"
          git push
